name: CI
on:
  pull_request:
    paths-ignore:
      - "documents/**"
      - "**.md"
  push:
    paths-ignore:
      - "documents/**"
      - "**.md"
  workflow_dispatch:

jobs:
  # ---------------------------------------------------------------------------
  ubuntu:
    strategy:
      matrix:
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    name: Ubuntu
    runs-on: ubuntu-24.04 # noble
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
          sudo apt-get install clang clang-tools lld xmake
      - name: Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
      - name: Build
        run: xmake b -v
      - name: Check UWVM version
        run: xmake run uwvm --version
      - name: Unit tests
        run: xmake test -vD
  # ---------------------------------------------------------------------------
  msys2:
    if: ${{ !always() }} # Remove it once update to LLVM21
    strategy:
      matrix:
        env:
          - name: "CLANG64"
            prefix: mingw-w64-clang-x86_64
          - name: "CLANGARM64"
            prefix: mingw-w64-clang-aarch64
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    name: MINGW ${{ matrix.env.name }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.env.name }}
          update: true
          install: |
            ${{ matrix.env.prefix }}-cc
            ${{ matrix.env.prefix }}-xmake
      - name: Configure
        run: xmake f -p mingw --use-llvm=y -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
      - name: Build
        run: xmake b -v
      - name: Check UWVM version
        run: xmake run uwvm --version
      - name: Unit tests
        run: xmake test -vD
  # ---------------------------------------------------------------------------
  freebsd:
    strategy:
      matrix:
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          version: "14.2"
          run: |
            sudo pkg install -y llvm-devel xmake-io
            xmake f -m debug -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
            xmake b -v
            xmake run uwvm --version
            xmake test -vD
